name: Auto Decrypt SH Files

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  decrypt:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Install GPG
      - name: Install GPG
        run: sudo apt-get update && sudo apt-get install -y gnupg

      # 3️⃣ Detect & Decrypt .sh files
      - name: Decrypt .sh files
        run: |
          set -e
          for f in $(find . -type f -name "*.sh"); do
            echo "[*] Checking $f ..."

            if grep -a -q "gpg -q --decrypt" "$f"; then
              echo "  ↳ Detected: GPG encrypted"

              PASS=$(grep -a -oP "(?<=--passphrase ['\"])[^'\"]+" "$f" | head -n1)
              [ -z "$PASS" ] && echo "  [!] No passphrase found in $f" && continue

              SKIP=$(grep -a -oP "(?<=tail -n \+)[0-9]+" "$f" | head -n1)
              [ -z "$SKIP" ] && SKIP=70

              echo "  ↳ Using passphrase (hidden), skip $SKIP lines"
              tail -n +$SKIP "$f" > "$f.encrypted"

              if gpg --batch --yes --passphrase "$PASS" -o "$f.decrypted" -d "$f.encrypted"; then
                echo "# Decrypted by GitHub Action" > "$f"
                cat "$f.decrypted" >> "$f"
                rm "$f.encrypted" "$f.decrypted"
                echo "  [✓] Decrypted $f (GPG)"
              else
                echo "  [!] Failed to decrypt $f with GPG"
                rm -f "$f.encrypted" "$f.decrypted"
              fi

            elif grep -a -q "eval" "$f"; then
              echo "  ↳ Detected: SHC / eval encrypted"

              cp "$f" "$f.bak"
              sed 's/eval/echo/' "$f" > "$f.temp"
              bash "$f.temp" > "$f.out" || true

              if [ -s "$f.out" ]; then
                echo "# Decrypted by GitHub Action" > "$f"
                cat "$f.out" >> "$f"
                rm "$f.temp" "$f.out" "$f.bak"
                echo "  [✓] Decrypted $f (SHC)"
              else
                echo "  [!] Failed to decrypt $f (SHC)"
                mv "$f.bak" "$f"
                rm -f "$f.temp" "$f.out"
              fi

            elif grep -a -q "base64 -d" "$f"; then
              echo "  ↳ Detected: Base64 encoded"

              cp "$f" "$f.bak"
              bash "$f" > "$f.out" || true

              if [ -s "$f.out" ]; then
                echo "# Decrypted by GitHub Action" > "$f"
                cat "$f.out" >> "$f"
                rm "$f.out" "$f.bak"
                echo "  [✓] Decrypted $f (Base64)"
              else
                echo "  [!] Failed to decrypt $f (Base64)"
                mv "$f.bak" "$f"
                rm -f "$f.out"
              fi

            else
              echo "  ↳ No encryption detected, skipping"
            fi
          done

      # 4️⃣ Commit & Push decrypted files
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-decrypted .sh files" || echo "No changes to commit"
          git push
