name: Auto Detect & Decrypt SH

on:
  workflow_dispatch:

jobs:
  decrypt:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Install deps
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg openssl xxd

      # 3️⃣ Detect & decrypt
      - name: Detect & Decrypt .sh
        run: |
          for f in $(find . -type f -name "*.sh"); do
            echo "[*] Checking $f ..."

            if grep -q "gpg -q --decrypt" "$f"; then
              echo "  [+] Detected: GPG Encrypted Loader"
              SKIP=$(grep -m1 "^skip=" "$f" | cut -d= -f2)
              [ -z "$SKIP" ] && SKIP=70
              PASS=$(grep -oP "(?<=--passphrase ')[^']+" "$f" | head -n1)
              echo "    ↳ Using passphrase: ${PASS:0:8}..."
              if tail -n +$SKIP "$f" | gpg --batch --yes --passphrase "$PASS" -d > "$f.dec"; then
                echo "# Decrypted by GitHub Action" > "$f"
                cat "$f.dec" >> "$f"
                rm "$f.dec"
                echo "  [✓] Decrypted $f"
              else
                echo "  [!] Failed to decrypt $f"
              fi

            elif grep -q "shc" "$f"; then
              echo "  [+] Detected: shc compiled shell script (binary)"
              echo "  [!] Cannot auto-decrypt SHC binaries without source"

            elif grep -q "base64 -d" "$f"; then
              echo "  [+] Detected: Base64 encoded script"
              PAYLOAD=$(grep -A50 "base64 -d" "$f" | grep -oP "[A-Za-z0-9+/=]{20,}" | head -n1)
              echo "$PAYLOAD" | base64 -d > "$f.dec" 2>/dev/null || true
              if [ -s "$f.dec" ]; then
                echo "# Decoded by GitHub Action" > "$f"
                cat "$f.dec" >> "$f"
                rm "$f.dec"
                echo "  [✓] Base64 decoded $f"
              fi

            elif grep -q "openssl enc" "$f"; then
              echo "  [+] Detected: OpenSSL encrypted script"
              echo "  [!] Manual password required, skipping"

            elif grep -q "xor" "$f"; then
              echo "  [+] Detected: XOR obfuscation"
              echo "  [!] Need custom XOR key, skipping"

            else
              echo "  [-] No encryption detected"
            fi
          done

      # 4️⃣ Commit & Push
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-decrypted .sh files" || echo "Nothing to commit"
          git push
