name: Auto Decrypt SH Files

on:
  workflow_dispatch:

jobs:
  decrypt:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Install deps
      - name: Install GPG & Python
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg python3

      # 3️⃣ Decrypt all .sh files
      - name: Decrypt .sh files
        run: |
          set -e
          for f in $(find . -type f -name "*.sh"); do
            echo "[*] Checking $f ..."
            
            if grep -a -q "gpg -q --decrypt" "$f"; then
              echo "  ↳ Detected GPG encrypted script"

              # Extract passphrase
              PASS=$(grep -a -oP "(?<=--passphrase ['\"])[^'\"]+" "$f" | head -n1)
              [ -z "$PASS" ] && echo "  [!] No passphrase found in $f" && continue

              # Extract skip line (default 70)
              SKIP=$(grep -a -oP "(?<=tail -n \+)[0-9]+" "$f" | head -n1)
              [ -z "$SKIP" ] && SKIP=70

              echo "  ↳ Passphrase found (hidden)"
              echo "  ↳ Skipping first $SKIP lines"

              tail -n +$SKIP "$f" > "$f.encrypted"

              if gpg --batch --yes --passphrase "$PASS" -o "$f.decrypted" -d "$f.encrypted"; then
                echo "# Decrypted by GitHub Action" > "$f"
                cat "$f.decrypted" >> "$f"
                rm "$f.encrypted" "$f.decrypted"
                echo "  [✓] Decrypted $f (GPG)"
              else
                echo "  [!] Failed to decrypt $f (GPG)"
                rm -f "$f.encrypted" "$f.decrypted"
              fi

            else
              echo "  ↳ Trying SHC style decryption ..."
              # Replace eval with echo and run
              if grep -a -q "eval" "$f"; then
                cp "$f" "$f.bak"
                sed 's/eval/echo/' "$f" > "$f.temp"
                bash "$f.temp" > "$f.out" || true

                if [ -s "$f.out" ]; then
                  echo "# Decrypted by GitHub Action" > "$f"
                  cat "$f.out" >> "$f"
                  rm "$f.temp" "$f.out"
                  echo "  [✓] Decrypted $f (SHC)"
                else
                  echo "  [!] Failed to decrypt $f (SHC)"
                  mv "$f.bak" "$f" # restore
                  rm -f "$f.temp" "$f.out"
                fi
              else
                echo "  ↳ No decryption needed for $f"
              fi
            fi
          done

      # 4️⃣ Commit & Push
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-decrypted .sh files" || echo "No changes to commit"
          git push
